version: "3"

networks:
  wordpress:
    driver: bridge

services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wordpress

  db:
    image: mysql:5.7
    ports:
      - 9903:3306
    environment:
      MYSQL_DATABASE: db_example
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - wordpress

  php:
    build: ./php
    ports:
      - 9000:9000
    #env_file:
    #  - ./path/to/custom/env-file/.env
    volumes:
      - ./website:/var/www/html
    networks:
      - wordpress

  nginx:
    build: ./server
    volumes:
      - ./website:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - php
      - db
      - mailhog
    networks:
      - wordpress

volumes:
  db-data:
